### PR TITLE
fix: issue with serialisation, closes #248

### LINKED ISSUE #248: Fix "stop pooling" button
When a user wants to stop pooling they click "stop pooling" on stacking-info page: https://earn.leather.io/pooled-stacking-info?chain=mainnet and expect a popup to come up to sign. 

Image
color of the text changes after clicking, that is all...

Image

That doesn't happen and they are stuck without the option to unstack. 

I see this issue with software and hardware mode Leather extension.

### PR DESCRIPTION
**Pull request by kyranjamie**
Issue was caused by bad serialisation of fns

### CODE REVIEW

File: src/pages/stacking/pooled-stacking-info/pooled-stacking-info.tsx [hunk 1]
```diff
@@ -97,25 +97,28 @@ function PooledStackingInfoLayout({ client }: CardLayoutProps) {
...
+
+      // Serialisation inside Connect breaks when we pass fns
+      const { client: _client, ...txConfig } = revokeDelegationOptions;
+
+      setIsContractCallExtensionPageOpen(true);
+      openContractCall({
+        // Type coercion necessary because the `network` property returned by
+        // `client.getStackingContract()` has a wider type than allowed by `showContractCall`. Despite
+        // the wider type, the actual value of `network` is always of the type `StacksNetwork`
+        // expected by `showContractCall`.
```
Comment (camerow) [inline src/pages/stacking/pooled-stacking-info/pooled-stacking-info.tsx:112]:
```suggestion
        // expected by `openContractCall`.
```

**Review by camerow — APPROVED** [review]

**Review by alter-eggo — APPROVED** [review]

**Comment by 314159265359879** [comment]
Thanks for the quick fix, looking good now!
